CREATE OR REPLACE PROCEDURE DISP_GUIDE (I_GUIDE_NUM IN GUIDE.GUIDE_NUM % TYPE) AS
   -- I_LAST_NAME  GUIDE.LAST_NAME % TYPE; # I
   -- I_FIRST_NAME GUIDE.FIRST_NAME%TYPE;

      BEGIN
   --    SELECT LAST_NAME, FIRST_NAME
   --    INTO I_LAST_NAME, I_FIRST_NAME
   --    FROM GUIDE
   --    WHERE GUIDE_NUM = I_GUIDE_NUM;

   --    DBMS_OUTPUT.PUT_LINE(I_GUIDE_NUM);
   --    DBMS_OUTPUT.PUT_LINE(RTRIM(I_FIRST_NAME) || ' ' ||RTRIM(I_LAST_NAME));
   END;

