
-- CREATE VIEW BIKING AS

-- select * from trip where (type = 'Biking' );

# Q1
-- CREATE VIEW MAINE_TRIPS AS
-- SELECT TRIP_ID, TRIP_NAME, START_LOCATION, DISTANCE, MAX_GRP_SIZE, TYPE, SEASON FROM TRIP
-- WHERE (STATE = 'ME');

# Q1 - b
-- SELECT TRIP_ID, TRIP_NAME, DISTANCE FROM MAINE_TRIPS WHERE ( TYPE = 'Biking');

# Q1 - c
-- SELECT TRIP_ID, TRIP_NAME, START_LOCATION, DISTANCE, MAX_GRP_SIZE, TYPE, SEASON FROM TRIP
--  WHERE (STATE = 'ME') AND ( TYPE = 'Biking');

# Q2 - a
-- create VIEW RESERVATION_CUSTOMER AS
--  SELECT R.RESERVATION_ID, TRIP_ID, TRIP_DATE, C.CUSTOMER_NUM, LAST_NAME, FIRST_NAME, PHONE FROM CUSTOMER C, RESERVATION R
--  WHERE (C.CUSTOMER_NUM = R.CUSTOMER_NUM);

# Q2 - b
-- SELECT * from RESERVATION_CUSTOMER WHERE (TRIP_DATE = '2016-09-11');

# Q3 - a
-- CREATE VIEW TRIP_INVENTORY2 AS
-- SELECT COUNT( * ) AS BANANAS, STATE FROM TRIP GROUP BY STATE;

-- # Q3 - b
-- SELECT STATE, UNITS FROM TRIP_INVENTORY WHERE ( UNITS > 10 );

# Q3- c
SELECT COUNT( * ) AS UNITS, STATE FROM TRIP GROUP BY STATE HAVING ( COUNT(*) > 10 ) ORDER BY STATE ASC;