
CREATE TABLE ENTRIES
(
	LOGIN VARCHAR( 50 ) NOT NULL,
	PASSWORD VARCHAR( 50 ) NOT NULL,
	EMAIL VARCHAR( 50 ) NOT NULL,
	PRIMARY KEY( LOGIN, PASSWORD, EMAIL )
);

INSERT INTO ENTRIES( LOGIN, PASSWORD, EMAIL ) VALUES( 'djulzz', 'vantorille1', 'julien.esposito@cc-sd.edu' );
